// src/plugin_main.cpp
// Notepad++ plugin lifecycle: setInfo, getName, getFuncsArray, beNotified,
// messageProc.  Also manages the GrammarRegistry and StyleMap singletons.
//
// IMPORTANT: Notepad++ requires a style XML file named <DLLName>.xml in the
// plugins\Config\ directory.  If it is missing, Notepad++ refuses to load
// the lexer plugin.  We generate this file in setInfo() (called early in
// the load sequence) if it does not already exist.
#include "plugin_main.h"
#include "ts_lexer_bridge.h"

#include <filesystem>
#include <fstream>
#include <string>
#include <cwchar>

#include <windows.h>

namespace fs = std::filesystem;

namespace npp_ts {

// ============================================================================
// Global singletons
// ============================================================================

static NppData         g_npp_data{};
static HINSTANCE       g_hModule = nullptr;
static GrammarRegistry g_registry;
static StyleMap        g_style_map;
static bool            g_initialized = false;

// The menu items we expose.
static FuncItem g_func_items[2];

// Plugin config directory (filled in by setInfo).
static std::string g_config_dir;
// Notepad++'s plugins\Config directory (parent of our own config dir).
static std::string g_npp_plugin_config_dir;

// Launch counter state.
static int  g_launch_count   = 0;
static bool g_support_suppressed = false;

// ============================================================================
// Helpers
// ============================================================================

static std::string get_npp_plugin_config_dir() {
    wchar_t buf[MAX_PATH]{};
    SendMessageW(g_npp_data.nppHandle, NPPM_GETPLUGINSCONFIGDIR,
                 MAX_PATH, reinterpret_cast<LPARAM>(buf));
    char narrow[MAX_PATH]{};
    WideCharToMultiByte(CP_UTF8, 0, buf, -1, narrow, MAX_PATH, nullptr, nullptr);
    return std::string(narrow);
}

static std::string get_config_dir() {
    auto dir = fs::path(g_npp_plugin_config_dir) / "NppTreeSitter";
    fs::create_directories(dir);
    return dir.string();
}

// ---------------------------------------------------------------------------
// Style XML generation.
//
// Notepad++ expects a file called NppTreeSitter.xml in the plugins\Config\
// directory.  This file must contain <LexerType> entries for every language
// the plugin provides, otherwise Notepad++ shows the "is missing / not
// compatible" error and refuses to load the lexer.
//
// We generate a default XML from the style map if it doesn't exist.
// Users can edit the generated file via Settings → Style Configurator.
// ---------------------------------------------------------------------------

static void ensure_style_xml() {
    auto xml_path = fs::path(g_npp_plugin_config_dir) / "NppTreeSitter.xml";

    // Don't overwrite if the user has already placed / edited one.
    if (fs::exists(xml_path)) return;

    // At this point grammars haven't been scanned yet (that happens in
    // initialize()), so we pre-scan the grammar directories just to get
    // names and extensions — enough to write the XML skeleton.
    auto ts_config_dir = fs::path(g_npp_plugin_config_dir) / "NppTreeSitter";
    auto grammars_dir  = ts_config_dir / "grammars";

    // Collect grammar names + extensions.
    struct LangInfo {
        std::string name;
        std::string extensions;  // space-separated, no dots
    };
    std::vector<LangInfo> langs;

    if (fs::is_directory(grammars_dir)) {
        for (auto& entry : fs::directory_iterator(grammars_dir)) {
            if (!entry.is_directory()) continue;
            std::string name = entry.path().filename().string();

            // Read extensions.txt
            std::string exts;
            auto ext_file = entry.path() / "extensions.txt";
            if (fs::exists(ext_file)) {
                std::ifstream f(ext_file);
                std::string line;
                while (std::getline(f, line)) {
                    while (!line.empty() && (line.back() == '\r' || line.back() == ' '))
                        line.pop_back();
                    if (line.empty()) continue;
                    // Strip leading dot for the ext="" attribute.
                    if (line.front() == '.') line.erase(line.begin());
                    if (!exts.empty()) exts += ' ';
                    exts += line;
                }
            }

            langs.push_back({name, exts});
        }
    }

    // If no grammars found, write a minimal empty XML so Notepad++ is happy.
    std::ofstream out(xml_path, std::ios::binary);
    if (!out.is_open()) return;

    out << "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n";
    out << "<!-- Auto-generated by NppTreeSitter. Edit via Style Configurator. -->\n";
    out << "<NotepadPlus>\n";
    out << "    <LexerStyles>\n";

    // Default style palette — uses colours that work on light backgrounds.
    // bgColor is intentionally omitted so Notepad++ inherits the background
    // from the active theme.  Users can override via Style Configurator.
    // fontStyle: Italic=1, Bold=2, Underline=4
    struct DefaultStyle {
        int id;
        const char* name;
        const char* fg;
        int fontStyle;
    };
    static constexpr DefaultStyle defaults[] = {
        { 0, "Default",               "000000", 0},
        { 1, "Keyword",               "0000FF", 2},
        { 2, "Keyword (function)",    "0000FF", 2},
        { 3, "Keyword (return)",      "0000FF", 2},
        { 4, "Keyword (operator)",    "8B008B", 0},
        { 5, "String",                "A31515", 0},
        { 6, "String (special)",      "B56508", 0},
        { 7, "Number",                "098658", 0},
        { 8, "Float",                 "098658", 0},
        { 9, "Function",              "795E26", 0},
        {10, "Function (builtin)",    "795E26", 1},
        {11, "Function (call)",       "795E26", 0},
        {12, "Method",                "795E26", 0},
        {13, "Method (call)",         "795E26", 0},
        {14, "Type",                  "267F99", 0},
        {15, "Type (builtin)",        "267F99", 1},
        {16, "Type (qualifier)",      "267F99", 2},
        {17, "Variable",              "001080", 0},
        {18, "Variable (builtin)",    "001080", 1},
        {19, "Variable (parameter)",  "001080", 1},
        {20, "Property",              "001080", 0},
        {21, "Field",                 "001080", 0},
        {22, "Constant",              "0070C1", 2},
        {23, "Constant (builtin)",    "0070C1", 3},
        {24, "Comment",               "008000", 0},
        {25, "Operator",              "000000", 0},
        {26, "Punctuation",           "505050", 0},
        {27, "Bracket",               "AF00DB", 0},
        {28, "Delimiter",             "505050", 0},
        {29, "Label",                 "8B008B", 0},
        {30, "Attribute",             "267F99", 1},
        {31, "Constructor",           "267F99", 0},
    };

    for (auto& lang : langs) {
        out << "        <LexerType name=\"" << lang.name
            << "\" desc=\"" << lang.name << " (TreeSitter)\"";
        if (!lang.extensions.empty())
            out << " ext=\"" << lang.extensions << "\"";
        out << ">\n";

        for (auto& s : defaults) {
            out << "            <WordsStyle styleID=\"" << s.id
                << "\" name=\"" << s.name
                << "\" fgColor=\"" << s.fg
                << "\" fontStyle=\"" << s.fontStyle
                << "\" />\n";
        }

        out << "        </LexerType>\n";
    }

    out << "    </LexerStyles>\n";
    out << "</NotepadPlus>\n";
}

// ---------------------------------------------------------------------------
// Persistent state — tracks launch count and "don't show again" flag.
// Stored in a simple key=value file: <config_dir>/state.conf
// ---------------------------------------------------------------------------

static std::string state_file_path() {
    return (fs::path(g_npp_plugin_config_dir) / "NppTreeSitter" / "state.conf").string();
}

static void load_state() {
    std::ifstream f(state_file_path());
    if (!f.is_open()) return;

    std::string line;
    while (std::getline(f, line)) {
        // Strip \r
        while (!line.empty() && line.back() == '\r') line.pop_back();

        auto eq = line.find('=');
        if (eq == std::string::npos) continue;

        std::string key = line.substr(0, eq);
        std::string val = line.substr(eq + 1);

        if (key == "launch_count") {
            try { g_launch_count = std::stoi(val); } catch (...) {}
        } else if (key == "support_suppressed") {
            g_support_suppressed = (val == "1" || val == "true");
        }
    }
}

static void save_state() {
    // Ensure the directory exists.
    auto dir = fs::path(g_npp_plugin_config_dir) / "NppTreeSitter";
    fs::create_directories(dir);

    std::ofstream f(state_file_path(), std::ios::binary);
    if (!f.is_open()) return;

    f << "launch_count=" << g_launch_count << "\n";
    f << "support_suppressed=" << (g_support_suppressed ? "1" : "0") << "\n";
}

// ---------------------------------------------------------------------------

static void initialize() {
    if (g_initialized) return;
    g_initialized = true;

    g_config_dir = get_config_dir();

    // Try to load a custom style map; fall back to defaults.
    auto style_cfg = (fs::path(g_config_dir) / "styles.conf").string();
    if (!g_style_map.load_from_file(style_cfg))
        g_style_map.load_defaults();

    // Scan for grammars.
    g_registry.scan(g_config_dir);

    // Load persistent state and increment launch counter.
    load_state();
    g_launch_count++;
    save_state();
}

// ---- Menu commands ----
static void about_cmd() {
    MessageBoxW(g_npp_data.nppHandle,
                L"NppTreeSitter \u2014 tree-sitter-based syntax highlighting for Notepad++.\n\n"
                L"Place grammar directories under:\n"
                L"  <config>/NppTreeSitter/grammars/<lang>/\n\n"
                L"Each directory should contain:\n"
                L"  grammar.dll, highlights.scm, extensions.txt\n\n"
                L"The style XML (NppTreeSitter.xml) is auto-generated\n"
                L"in plugins\\Config\\ on first run.",
                L"NppTreeSitter", MB_OK | MB_ICONINFORMATION);
}

// ---------------------------------------------------------------------------
// Support / Donate dialog — uses a SysLink control for a clickable URL.
// Falls back to a plain MessageBox + ShellExecute if SysLink fails.
// ---------------------------------------------------------------------------

#include <shellapi.h>
#include <commctrl.h>

static const wchar_t* PATREON_URL = L"https://www.patreon.com/cw/BenMordaunt";

// Dialog return codes.
static constexpr INT_PTR SUPPORT_DLG_OK          = 1;
static constexpr INT_PTR SUPPORT_DLG_DONT_SHOW   = 2;
static constexpr int     IDC_DONT_SHOW           = 102;

static INT_PTR CALLBACK SupportDlgProc(HWND hDlg, UINT msg,
                                        WPARAM wParam, LPARAM lParam)
{
    switch (msg) {
    case WM_INITDIALOG:
        return TRUE;

    case WM_COMMAND:
        if (LOWORD(wParam) == IDOK || LOWORD(wParam) == IDCANCEL) {
            EndDialog(hDlg, SUPPORT_DLG_OK);
            return TRUE;
        }
        if (LOWORD(wParam) == IDC_DONT_SHOW) {
            EndDialog(hDlg, SUPPORT_DLG_DONT_SHOW);
            return TRUE;
        }
        break;

    case WM_NOTIFY: {
        auto* nmhdr = reinterpret_cast<NMHDR*>(lParam);
        if (nmhdr->code == NM_CLICK || nmhdr->code == NM_RETURN) {
            ShellExecuteW(nullptr, L"open", PATREON_URL, nullptr, nullptr, SW_SHOWNORMAL);
            return TRUE;
        }
        break;
    }
    }
    return FALSE;
}

static void support_cmd() {
    // Build a dialog template in memory.  This avoids the need for a
    // separate .rc resource file, keeping the plugin as a single source
    // build with no resource compiler dependency.
    //
    // The dialog contains:
    //   - A static text label (prompt)
    //   - A SysLink control (clickable URL)
    //   - An OK button
    //   - A "Don't Show Again" button

#pragma pack(push, 4)
    struct {
        DLGTEMPLATE dlg;
        WORD menu;      // no menu
        WORD wndClass;  // default class
        wchar_t title[24];

        // --- Item 1: static text ---
        DWORD align1;
        DLGITEMTEMPLATE item1;
        WORD item1Class[2];  // 0xFFFF, 0x0082 = STATIC
        wchar_t item1Text[80];
        WORD item1Extra;

        // --- Item 2: SysLink ---
        DWORD align2;
        DLGITEMTEMPLATE item2;
        wchar_t item2ClassName[8];  // L"SysLink"
        wchar_t item2Text[128];
        WORD item2Extra;

        // --- Item 3: OK button ---
        DWORD align3;
        DLGITEMTEMPLATE item3;
        WORD item3Class[2];  // 0xFFFF, 0x0080 = BUTTON
        wchar_t item3Text[4];
        WORD item3Extra;

        // --- Item 4: Don't Show Again button ---
        DWORD align4;
        DLGITEMTEMPLATE item4;
        WORD item4Class[2];  // 0xFFFF, 0x0080 = BUTTON
        wchar_t item4Text[20];
        WORD item4Extra;
    } tmpl{};
#pragma pack(pop)

    // Dialog
    tmpl.dlg.style = DS_MODALFRAME | DS_CENTER | WS_POPUP | WS_CAPTION | WS_SYSMENU | DS_SETFONT;
    tmpl.dlg.cdit  = 4;
    tmpl.dlg.cx    = 220;
    tmpl.dlg.cy    = 110;
    tmpl.menu      = 0;
    tmpl.wndClass  = 0;
    wcscpy(tmpl.title, L"Support NppTreeSitter");

    // Item 1: static label
    tmpl.item1.style = WS_CHILD | WS_VISIBLE | SS_CENTER;
    tmpl.item1.x  = 10;  tmpl.item1.y  = 10;
    tmpl.item1.cx = 200; tmpl.item1.cy = 28;
    tmpl.item1.id = 100;
    tmpl.item1Class[0] = 0xFFFF;
    tmpl.item1Class[1] = 0x0082;  // STATIC
    wcscpy(tmpl.item1Text,
           L"NppTreeSitter is free and open source.\r\n"
           L"If you find it useful, please consider supporting\r\n"
           L"its development on Patreon:");
    tmpl.item1Extra = 0;

    // Item 2: SysLink
    tmpl.item2.style = WS_CHILD | WS_VISIBLE | WS_TABSTOP;
    tmpl.item2.x  = 10;  tmpl.item2.y  = 45;
    tmpl.item2.cx = 200; tmpl.item2.cy = 14;
    tmpl.item2.id = 101;
    wcscpy(tmpl.item2ClassName, L"SysLink");
    wcscpy(tmpl.item2Text,
           L"<a href=\"https://www.patreon.com/cw/BenMordaunt\">"
           L"https://www.patreon.com/cw/BenMordaunt</a>");
    tmpl.item2Extra = 0;

    // Item 3: OK button
    tmpl.item3.style = WS_CHILD | WS_VISIBLE | WS_TABSTOP | BS_DEFPUSHBUTTON;
    tmpl.item3.x  = 40;  tmpl.item3.y  = 70;
    tmpl.item3.cx = 50;  tmpl.item3.cy = 14;
    tmpl.item3.id = IDOK;
    tmpl.item3Class[0] = 0xFFFF;
    tmpl.item3Class[1] = 0x0080;  // BUTTON
    wcscpy(tmpl.item3Text, L"OK");
    tmpl.item3Extra = 0;

    // Item 4: Don't Show Again button
    tmpl.item4.style = WS_CHILD | WS_VISIBLE | WS_TABSTOP;
    tmpl.item4.x  = 110; tmpl.item4.y  = 70;
    tmpl.item4.cx = 72;  tmpl.item4.cy = 14;
    tmpl.item4.id = IDC_DONT_SHOW;
    tmpl.item4Class[0] = 0xFFFF;
    tmpl.item4Class[1] = 0x0080;  // BUTTON
    wcscpy(tmpl.item4Text, L"Don't Show Again");
    tmpl.item4Extra = 0;

    // Ensure common controls are loaded (needed for SysLink).
    INITCOMMONCONTROLSEX icc{};
    icc.dwSize = sizeof(icc);
    icc.dwICC  = ICC_LINK_CLASS;
    InitCommonControlsEx(&icc);

    INT_PTR result = DialogBoxIndirectW(
        nullptr,
        &tmpl.dlg,
        g_npp_data.nppHandle,
        SupportDlgProc
    );

    if (result == SUPPORT_DLG_DONT_SHOW) {
        g_support_suppressed = true;
        save_state();
    }

    // Fallback if the dialog failed (e.g. SysLink not available under Wine).
    if (result == -1) {
        int choice = MessageBoxW(
            g_npp_data.nppHandle,
            L"NppTreeSitter is free and open source.\n\n"
            L"If you find it useful, please consider supporting\n"
            L"its development on Patreon:\n\n"
            L"https://www.patreon.com/cw/BenMordaunt\n\n"
            L"Click YES to open the Patreon page.\n"
            L"Click NO to never show this again.\n"
            L"Click CANCEL to dismiss.",
            L"Support NppTreeSitter",
            MB_YESNOCANCEL | MB_ICONINFORMATION
        );
        if (choice == IDYES) {
            ShellExecuteW(nullptr, L"open", PATREON_URL, nullptr, nullptr, SW_SHOWNORMAL);
        } else if (choice == IDNO) {
            g_support_suppressed = true;
            save_state();
        }
    }
}

// ============================================================================
// Plugin exports (called by Notepad++ via the DLL interface)
// ============================================================================

void plugin_setInfo(NppData nppData) {
    g_npp_data = nppData;

    // This is called early — before Notepad++ checks for the style XML.
    // Generate the XML now if it's missing.
    g_npp_plugin_config_dir = get_npp_plugin_config_dir();
    ensure_style_xml();
}

const wchar_t* plugin_getName() {
    return L"NppTreeSitter";
}

FuncItem* plugin_getFuncsArray(int* nbF) {
    std::wcsncpy(g_func_items[0].itemName, L"About NppTreeSitter", nbChar - 1);
    g_func_items[0].itemName[nbChar - 1] = L'\0';
    g_func_items[0].pFunc     = about_cmd;
    g_func_items[0].cmdID     = 0;
    g_func_items[0].init2Check = false;
    g_func_items[0].pShKey    = nullptr;

    std::wcsncpy(g_func_items[1].itemName, L"Support this plugin...", nbChar - 1);
    g_func_items[1].itemName[nbChar - 1] = L'\0';
    g_func_items[1].pFunc     = support_cmd;
    g_func_items[1].cmdID     = 0;
    g_func_items[1].init2Check = false;
    g_func_items[1].pShKey    = nullptr;

    *nbF = 2;
    return g_func_items;
}

void plugin_beNotified(SCNotification* notification) {
    switch (notification->nmhdr_code) {
    case NPPN_READY:
        initialize();

        // Show the support dialog every 5 launches, unless suppressed.
        if (!g_support_suppressed && g_launch_count > 0 &&
            (g_launch_count % 5) == 0) {
            support_cmd();
        }
        break;

    case NPPN_BUFFERACTIVATED:
    case NPPN_FILEOPENED:
        break;

    default:
        break;
    }
}

LRESULT plugin_messageProc(UINT /*msg*/, WPARAM /*wParam*/, LPARAM /*lParam*/) {
    return TRUE;
}

BOOL plugin_isUnicode() {
    return TRUE;
}

// ============================================================================
// Lexilla entry points
// ============================================================================

const GrammarRegistry& plugin_get_registry() {
    initialize();
    return g_registry;
}

const StyleMap& plugin_get_style_map() {
    return g_style_map;
}

} // namespace npp_ts
